decentralized-identity/sidetree

- docs/design.md
Added the following content to design doc:
1.  Proof-of-work requirement
2. 'payload' property to encapsulate all data that needs to be signed.
3. Various typo and minor fixes.
> Design doc - Added proof-of-work requirement + 'payload' for various Sidetree operations

- src/lib/MerkleTree.ts
- tests/lib/MerkleTree.spec.ts
Next will create the specification for the receipt in protocol doc.
> Merkle tree - Added receipt creation and proof functions.

- docs/implementation.md
- docs/protocol.md
- package-lock.json
- package.json
- src/Blockchain.ts
- src/Cas.ts
- src/Config.ts
- src/Protocol.ts
- src/Rooter.ts
- src/config.json
- src/index.ts
- src/protocol.json
1. Protocol doc - Added 'batch file' + 'anchor file' terminology and schema.
2. Implementation doc - Changed CAS REST API definitions + minor fixes.
3. Rooter - Added main rooting flow + configuration and protocol parameter loading.
> Rooter - Added main rooting flow + configuration and protocol parameter loading.

- docs/protocol.md
- package-lock.json
- package.json
- src/Config.ts
- src/Operation.ts
- src/Protocol.ts
- src/RequestHandler.ts
- src/Response.ts
- src/config.json
- src/index.ts
- src/protocol.json
There are a bunch of TODOs to be filled in, but the code demonstrates the overall structure.
> Request handling structure and write operation request parsing.

- docs/implementation.md
- docs/protocol.md
1. Simplified DID Cache apply method definition.
2. Simplified Blockchain REST API for fetching transactions.
3. Fixed typos in protocol.md.
> Documentation - Updated DID Cache and Blockchain API definitions.

- docs/implementation.md
- docs/protocol.md
- json/config.json
- json/protocol.json
- src/Block.ts
- src/Blockchain.ts
- src/Config.ts
- src/DidCache.ts
- src/Multihash.ts
- src/Observer.ts
- src/Operation.ts
- src/Protocol.ts
- src/RequestHandler.ts
- src/Rooter.ts
- src/Transaction.ts
- src/index.ts
- tests/Operation.spec.ts
- tests/Protocol.spec.ts
- tests/RequestHandler.spec.ts
- tests/mocks/MockBlockchain.ts
- tests/mocks/MockDidCache.ts
Observer - Wrote main observer logic.
Observer - Added polling interval in config and initialized Observer in index.ts.
Observer - Added transaction and operation size limit checks.
Observer - Added logic to tapper retries when encounter consecutive errors.
Blockchain API - Implemented fetching of last block info.
Blockchain API - Fixed transactions fetch definition and updated code accordingly.
Blockchain API - Added Sidetree transaction read interface and implementation.
Implementation doc - Added 404 return code for REST API.
Implementation doc - Removed outdated processing rules section.
Protocol doc - Added description for the concept of 'transaction number'.
Protocol doc - Added Sidetree transaction processing section.
Protocol - Fixed protocols reverse sorting bug + added test for …
> Observer logic + many code and documentation updates and fixes.

- tests/Config.spec.ts
- tests/Operation.spec.ts
- tests/Protocol.spec.ts
- tests/RequestHandler.spec.ts
- tests/lib/MerkleTree.spec.ts
- tests/mocks/MockBlockchain.ts
- tests/mocks/MockCas.ts
- tests/mocks/MockDidCache.ts
- tslint.json
Test code should have the same convention as feature code.
> Test - Enabled linter for test code + fixed all linter detected test code issues.

- json/config.json
- json/protocol-test.json
- json/protocol.json
- src/DidCache.ts
- src/Observer.ts
- src/Operation.ts
- src/Protocol.ts
- src/RequestHandler.ts
- src/Response.ts
- src/Rooter.ts
- src/Transaction.ts
- src/index.ts
- tests/DidCache.spec.ts
- tests/Protocol.spec.ts
- tests/RequestHandler.spec.ts
- tests/mocks/MockBlockchain.ts
- tests/mocks/MockDidCache.ts
- tests/mocks/MockDidDocumentGenerator.ts
- Request handler - Implemented resolve REST API.
- Request handler - Refactored create REST API.
- Protocol - Added ability to specify protocol parameter file.
- DID cache - Replace the mock DID Document create function with a real implementation.
- Operation - Added method to construct the initial DID Document from a create operation.
- Operation - Refactored factory to take multiple transaction params using a single ResolvedTransaction object.
- Observer - Refactored methods to pass/accept multiple transaction params using a single ResolvedTransaction object.
- Rooter - Fixed a bug where empty batch are still being serialized and rooted.
- Koa - Fixed a bug where an undefined koa response body results in an HTTP 204.
- Implemented a functioning mock Blockchain provider and using it …
> REST API - Implemented resolve request handling + code fixes & refactoring.

- docs/implementation.md
- docs/protocol.md
- json/protocol-test.json
- json/protocol.json
- src/Block.ts
- src/Blockchain.ts
- src/BlockchainTime.ts
- src/DidCache.ts
- src/Observer.ts
- src/Operation.ts
- src/Protocol.ts
- src/RequestHandler.ts
- src/Rooter.ts
- src/Transaction.ts
- tests/DidCache.spec.ts
- tests/Protocol.spec.ts
- tests/RequestHandler.spec.ts
- tests/mocks/MockBlockchain.ts
1. The concept of blockchain _*block*_ is no longer surfaced anywhere above the blockchain layer.
2. Simplified blockchain interface definition to allow stateless implementation.
> Abstracted away the concept of blockchain blocks + interface simplification

- src/Cache.ts
- src/OperationProcessor.ts
- src/OperationStore.ts
Add OperationStore class to cache and reduce OperationReconstruction costs
> AddOperationStoreClass

- package-lock.json
- package.json
- src/BatchFile.ts
- src/Observer.ts
- src/OperationStore.ts
- src/Rooter.ts
- src/lib/JsonAsync.ts
- tests/RequestHandler.spec.ts
* Batch file - Changed parsing to be asynchronous to minimize locking up of the main event loop.
* Operation store - Increased cache size by 2 magnitude + added a library to easily measure execution time.
> Batch file - Changed parsing to be async to minimize locking up of the main event loop.

- docs/implementation.md
- src/Blockchain.ts
- src/Error.ts
- src/Observer.ts
- src/OperationProcessor.ts
- src/RequestHandler.ts
- src/Rooter.ts
- tests/mocks/MockBlockchain.ts
1. Implementation documentation - Replaced the 'trace' API with 'firstValid' API.
1. Blockchain client - Added getFirstValidTransaction() interface and implementation.
1. Observer - Implemented block reorganization detection and handling.
1. Various logging improvements.
> Implemented block reorganization detection and handling in the Observer

- docs/protocol.md
1. Changed protocol to use request payload for operation hash calculation.
1. Fixed encoding scheme typo.
> Protocol - Changed spec to use request payload for operation hash calculation.

- docs/protocol.md
- json/config-test.json
- package-lock.json
- package.json
- src/Multihash.ts
- src/Operation.ts
- src/OperationProcessor.ts
- src/Protocol.ts
- src/RequestHandler.ts
- src/index.ts
- src/lib/Did.ts
- src/lib/Document.ts
- tests/OperationProcessor.spec.ts
- tests/RequestHandler.spec.ts
- tests/generators/VegetaLoadGenerator.ts
- tests/lib/Document.spec.ts
1. Added spec for resolution using an encoded original DID Document.
1. Added support for resolution using an encoded original DID Document.
1. Various minor fixes including naming convention, terminology, typos etc.
> Added support for DID resolution using an encoded original DID Document

- docs/protocol.md
- src/Observer.ts
- src/Operation.ts
- src/RequestHandler.ts
- src/lib/Document.ts
- tests/OperationProcessor.spec.ts
- tests/RequestHandler.spec.ts
- tests/generators/VegetaLoadGenerator.ts
- tests/json/didDocumentTemplate.json
- tests/lib/Document.spec.ts
1. Added code structure for original DID Document validation.
1. Added basic rules (for issue https://github.com/decentralized-identity/sidetree-core/issues/119) for original DID Document validation.
> Added structure and basic rules for original DID Document validation.

- docs/implementation.md
- docs/protocol.md
- src/Observer.ts
- src/Operation.ts
- src/OperationProcessor.ts
- src/OperationStore.ts
- src/RequestHandler.ts
- src/index.ts
- tests/Operation.spec.ts
- tests/OperationProcessor.spec.ts
- tests/RequestHandler.spec.ts
- tests/generators/OperationGenerator.ts
- tests/generators/VegetaLoadGenerator.ts
- tests/json/didDocumentTemplate.json
- tests/lib/Document.spec.ts
1. Protocol documentation - Updated request format to use flattened JWS JSON serialization.
1. Implemented JWS scheme for operation requests and updated all affected tests.
1. Renamed `WriteOperation` class to `Operation`.
1. Various minor fixes.
> Implemented JWS scheme for operation requests.

- docs/implementation.md
- docs/protocol.md
- src/Observer.ts
- src/Operation.ts
- src/OperationProcessor.ts
- src/RequestHandler.ts
- src/lib/Cryptography.ts
- tests/Operation.spec.ts
- tests/OperationProcessor.spec.ts
- tests/RequestHandler.spec.ts
- tests/generators/OperationGenerator.ts
- tests/generators/VegetaLoadGenerator.ts
1. Fixed bug #80 - Create operation with invalid signature should be rejected.
1. Added a test to prevent future regression.
> Fixed bug #80 - Create operation with invalid signature should be rejected.

- package-lock.json
- package.json
- src/Observer.ts
- src/Operation.ts
- src/lib/Document.ts
- tests/Observer.spec.ts
- tests/RequestHandler.spec.ts
Schema validation using yup slows down ingestion by around 10x, so must remove this dependency.
> Fixed issue 139 - Removed `yup` dependency due to its poor performance.

- docs/protocol.md
- src/Operation.ts
- tests/generators/OperationGenerator.ts
A fix to the reopened issue #122
> Added 'alg' as a required property in operation header to be JWS-compliant

- package-lock.json
- src/MongoDbOperationStore.ts
- src/OperationProcessor.ts
- src/OperationStore.ts
- src/index.ts
- tests/Observer.spec.ts
- tests/OperationProcessor.spec.ts
- tests/OperationStore.spec.ts
- tests/RequestHandler.spec.ts
- tests/mocks/MockOperationStore.ts
1. Addressed issue #149 by simplifying Operation Processor and Store initialization code.
1. Removed `OperationStore.put(...)` interface method.
1. Updated package-lock.json to fix 1 vulnerability.
> Simplified Operation Processor and Store initialization code

- src/MongoDbOperationStore.ts
- tests/OperationStore.spec.ts
- tests/mocks/MockOperationStore.ts
Make mongodb index unique to reject duplicate operations
> Fix for Issue 151

- lib/Blockchain.ts
- lib/BlockchainTime.ts
- lib/MongoDbOperationStore.ts
- lib/MongoDbTransactionStore.ts
- lib/Observer.ts
- lib/Operation.ts
- lib/Transaction.ts
- lib/TransactionStore.ts
- lib/util/Cryptography.ts
- lib/util/DidPublicKey.ts
- lib/util/MerkleTree.ts
- tests/MongoDbTransactionStore.spec.ts
- tests/RequestHandler.spec.ts
- tests/generators/OperationGenerator.ts
- tests/mocks/MockBlockchain.ts
> Fix naming inconsistency of data structure interfaces

- lib/core/MongoDbOperationStore.ts
- lib/core/Observer.ts
- lib/core/OperationProcessor.ts
- lib/core/OperationStore.ts
- tests/core/MongoDbOperationStore.spec.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/mocks/MockOperationStore.ts
> Rename `putBatch` to `put`, and `processBatch` to `process` 

- lib/bitcoin/README.md
- lib/core/Blockchain.ts
1. Core service - Added logging to Blockchain.firstValidTransaction() call.
1. Bitcoin service - Minor updates to example config file in README.md
> Core service - Added logging to Blockchain.firstValidTransaction() call

- lib/core/Blockchain.ts
Needs to be wrapped in a `transaction` property.
> Core service - Fixed bug where first-valid request is formed incorrectly

- lib/common/ErrorCode.ts
- lib/core/AnchorFile.ts
- lib/core/BatchWriter.ts
- lib/core/Multihash.ts
- lib/core/Observer.ts
- tests/core/AnchorFile.spec.ts
- tests/core/Observer.spec.ts
Issue #129 - Added Anchor File schema validation.BatchWriter to be a multihash.
Issue #246 - Made merkleRoot created by BatchWriter a multihash.
> Issue #129 - Anchor File schema validation & Issue #246 - merkleRoot not a multihash

- lib/bitcoin/BitcoinProcessor.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
> Ignore the transactions which have multiple OP_RETURN operations.

- lib/core/versions/0.5.0/Operation.ts
- lib/core/versions/latest/Document.ts
- lib/core/versions/latest/ErrorCode.ts
- lib/core/versions/latest/Operation.ts
- lib/core/versions/latest/OperationProcessor.ts
- lib/core/versions/latest/models/DidPublicKeyModel.ts
- lib/core/versions/latest/util/Cryptography.ts
- tests/core/MongoDbOperationStore.spec.ts
- tests/core/Observer.spec.ts
- tests/core/Operation.spec.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/generators/VegetaLoadGenerator.ts
Added controller as a property of the publickey but only the sidetree node adds an actual value to it. Adding by client is not allowed. #165
> #165 Added controller as a property of the publickey 

- lib/core/versions/latest/Document.ts
- lib/core/versions/latest/util/Cryptography.ts
- tests/core/MongoDbOperationStore.spec.ts
- tests/core/Observer.spec.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/core/util/Document.spec.ts
- tests/generators/VegetaLoadGenerator.ts
Fixing the bug where the did document could have the controller field in the publickey element.
> #165 Create should block the controller field in the publickey element.

- lib/core/versions/latest/Operation.ts
- tests/core/OperationProcessor.spec.ts
- Fix the condition that checks if a key is a recovery key
- Add test
> Fix removing a recovery key

- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/fee/SlidingWindowQuantileCalculator.ts
- lib/bitcoin/protocol-parameters.json
- lib/common/SharedErrorCode.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
These changes ensure that the bitcoin service runs successfully against testnet after our proof of fee changes. Issue #337 is also being fixed as a result of this work.
> #25 Integrated bitcoin service with bitcoin testnet

- .vscode/settings.json
- package.json
disables prettier in vscode settings.
> Prevent Prettier from fighting TSLint

- docs/implementation.md
- lib/bitcoin/BitcoinClient.ts
- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/SidetreeTransactionData.ts
- lib/bitcoin/models/BitcoinInputModel.ts
- lib/common/MongoDbTransactionStore.ts
- lib/common/models/TransactionModel.ts
- tests/bitcoin/BitcoinClient.spec.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/bitcoin/SidetreeTransactionData.spec.ts
- tests/bitcoin/SpendingMonitor.spec.ts
- tests/core/Blockchain.spec.ts
- tests/core/MongoDbTransactionStore.spec.ts
- tests/core/MongoDbUnresolvableTransactionStore.spec.ts
- tests/core/Observer.spec.ts
- tests/core/ThroughputLimiter.spec.ts
- tests/core/TransactionProcessor.spec.ts
- tests/core/TransactionSelector.spec.ts
- tests/core/VersionManager.spec.ts
- tests/mocks/MockBlockchain.ts
1. While reading the sidetree transaction, also read the writer.
1. Return the writer info for each transaction.
> #271 Parse and return the sidetree transaction writer (public key hash) 

- docs/protocol.md
JIC, the third one is only one word: "increased" instead of "increasing". 
Cheers!
> minor errors/typos fixed

- context-v1.jsonld
- docs/spec/markdown/context.md
- scripts/spec-render.js
- specs.json
Addresses: https://github.com/decentralized-identity/sidetree/issues/278
> Define sidetree context

- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/fee/SlidingWindowQuantileCalculator.ts
- lib/bitcoin/models/ProtocolParameters.ts
- lib/bitcoin/protocol-parameters.json
- tests/bitcoin/pof/SlidingWindowQuantileCalculator.spec.ts
Added a new factor parameter to make sure that the current quantile does not deviate too much from the previous quantile value.
> #395 Update the quantile calculator to smooth the fee curve

- docs/swagger/api.yml
- docs/swagger/index.html
Addresses: https://github.com/decentralized-identity/sidetree/issues/492
> Add Swagger API Spec

- lib/core/models/DidState.ts
- lib/core/versions/latest/DocumentComposer.ts
- lib/core/versions/latest/OperationProcessor.ts
- lib/core/versions/latest/RequestHandler.ts
- tests/core/RequestHandler.spec.ts
> make output did spec compliant

- docs/spec/markdown/file-structures.md
- docs/spec/markdown/terminology.md
- docs/spec/markdown/versioning.md
Troy found some broken links in Issue #504, which this PR corrects.
> Fix broken links from Issue #504

- docs/protocol.md
- lib/core/versions/latest/DocumentComposer.ts
- lib/core/versions/latest/ErrorCode.ts
- tests/core/DocumentComposer.spec.ts
- tests/generators/OperationGenerator.ts
address comments from @thehenrytsai 
- operation key validation
- key generator documentation
> validate operation keys

- docs/swagger/api.yml
Updated JSON properties to use underscores.
Closes: #579
> Update swagger API to use underscores

- lib/core/Core.ts
- lib/core/models/Config.ts
- package-lock.json
- package.json
- tests/core/Core.spec.ts
Minor fix to help run mainnet and testnet on the same mongodb.
Also updated nyc since that was causing audit errors and 'node not found'.
> Added "databaseName" to Core's config

- .github/workflows/ci.yml
- README.md
This is a pull request for this issue https://github.com/decentralized-identity/sidetree/issues/464
I added CI configuration for GitHub Actions.
Please close this pull request if you do not want it.
> #464 - Migrate CI to Github Actions

- context-v1.jsonld
> fix: update context path for spec

- docs/swagger/api.yml
- changes query parameters to kebab case.
- changes firstValid path to first-valid.
Closes: #624
> use kebab case for query parameters

- spec/markdown/operations.md
> spec: fixes duplicated text in recover operation

- spec/index.html
- spec/markdown/operations.md
- spec/markdown/rest-api.md
Would close out https://github.com/decentralized-identity/sidetree/issues/598
> Specify compact JWS for all references

- spec/markdown/patches.md
> Add capability usages to the add-public-keys action in spec

- contexts/sidetree-v0.0.0.jsonld
> Move Sidetree JSON-LD Context

- www/swagger/api.yml
- adds version endpoint.
- adds previous_hash to time response.
- splits up sidetree operation schemas.
- adds 410 http response code for deactivated DID.
- other minor fixes.
> Update swagger API

- www/swagger/api.yml
fixes indents for /blockchain/writerlock and /blockchain/version
> fix swagger indents

- docs/spec/method-versioning.md
Signed-off-by: Kyle Den Hartog <kyle.denhartog@mattr.global>
Addresses issue #590
> add warning about forking of decentralized ledger system

- contexts/sidetree-v0.0.0.jsonld
Signed-off-by: Kyle Den Hartog <kyle.denhartog@mattr.global>
This should close #612 and #615
@OR13 can you double check to make sure I did this right?
> update context document to remove publicKeyJwk and add JsonWebKey2020

- docs/spec/resolution.md
This PR resolves https://github.com/decentralized-identity/sidetree/issues/368
> Add @base SHOULD directive to resolution

- docs/spec/json-web-signatures.md
- docs/spec/patches.md
Addresses: https://github.com/decentralized-identity/sidetree/issues/659
> Define Operation Verification

- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/ErrorCode.ts
- lib/bitcoin/SidetreeTransactionParser.ts
- lib/bitcoin/fee/NormalizedFeeCalculator.ts
- lib/bitcoin/fee/SlidingWindowQuantileCalculator.ts
- tests/bitcoin/BitcoinDataGenerator.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/bitcoin/SidetreeTransactionParser.spec.ts
- tests/bitcoin/pof/NormalizedFeeCalculator.spec.ts
1. Moved the normalized fee calculation logic out to a new class `NormalizedFeeCalculator`.
1. Added some error codes to help with diagnosability (opportunistic fix).
> #678 Abstract out normalized-fee-calculator

- lib/index.ts
> #755 Adding IBitcoinWallet to the export list

- lib/bitcoin/fee/MongoDbSlidingWindowQuantileStore.ts
- lib/bitcoin/lock/MongoDbLockTransactionStore.ts
- lib/common/MongoDbTransactionStore.ts
- lib/core/MongoDbOperationStore.ts
- lib/core/MongoDbUnresolvableTransactionStore.ts
* Fixed all nodejs deprecation warnings seen when running the microservices.
* Fixed MongoDB test instabilities when run against cloud services such as CosmosDB.
> #87 - Fixed all nodejs deprecation warnings & and MongoDB test instabilities

- lib/core/versions/latest/ErrorCode.ts
- lib/core/versions/latest/RequestHandler.ts
- tests/core/RequestHandler.spec.ts
This is to help differentiate between path vs DID not found
> add error message for did not found

- www/spec/v0.1.0/index.html
Build of the spec from https://github.com/decentralized-identity/sidetree/commit/9c7d8677dad684f7e9d58445629503650ac8c1d6
> Release Spec v0.1.0

- www/spec/v0.1.0/index.html
Attempt to fix spec up styling issue.
> Fix spec v0.1.0 pathing

- README.md
Tweaks the root readme adding the npm badges for the reference implementation
> docs: update readme add npm badges

- lib/bitcoin/BitcoinProcessor.ts
- lib/core/versions/latest/TransactionProcessor.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
This is still needed by the core service until #814 is implemented.
> Reverted the removal of firstValidTransaction()

- .github/workflows/release.yml
- CHANGELOG.md
- commitlint.config.js
- docs/contribution-guidlines.md
- docs/release-process.md
- package-lock.json
- package.json
This PR adds support for automated changelog generation during the release process
**Note** - this will enforce a specific commit format from now on so the changelog can be automatically generated based on the changelog.
Looking for feedback on this approach and confirming it is not going to be a developer burden.
> build: add conventional changelog support

- docs/spec/patches.md
`s/JwsVerificationKey2020/JsonWebKey2020/g`
Closes: #825
> spec: switch to JsonWebKey2020

- docs/spec/patches.md
Update strings across all patch types to reflect agreed upon modifications.
> fix(spec): update patches to reflected agreed upon changes

- docs/protocol.md
- lib/common/LogColor.ts
- lib/common/models/TransactionModel.ts
- lib/core/versions/latest/AnchoredDataSerializer.ts
- lib/core/versions/latest/BatchWriter.ts
- lib/core/versions/latest/ChunkFile.ts
- lib/core/versions/latest/CoreIndexFile.ts
- lib/core/versions/latest/ErrorCode.ts
- lib/core/versions/latest/ProvisionalIndexFile.ts
- lib/core/versions/latest/TransactionProcessor.ts
- lib/core/versions/latest/models/AnchoredData.ts
- tests/core/AnchorFile.spec.ts
- tests/core/BatchWriter.spec.ts
- tests/core/ChunkFile.spec.ts
- tests/core/CoreProofFile.spec.ts
- tests/core/Observer.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/core/TransactionProcessor.spec.ts
- tests/core/TransactionSelector.spec.ts
- tests/core/util/AnchoredDataSerializer.spec.ts
- tests/generators/FileGenerator.ts
- tests/generators/OperationGenerator.ts
Changed the download and validation flow of Sidetree files to match decisions made in WG.
> feat(ref-imp): #766 - updated error handling for file downloading and validation

- docs/api/content.md
Also using `SUFFIX_STRING` instead of `DID_SUFFIX` to match its use elsewhere.
> fix(spec): mention JSON Compact Serialization in spec

- lib/core/Resolver.ts
- tests/core/MongoDbOperationStore.spec.ts
- tests/core/Observer.spec.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/Resolver.spec.ts
- 100% line code coverage
- Branch coverage will come next
> 100% line coverage

- lib/core/MongoDbOperationStore.ts
- lib/core/interfaces/IOperationStore.ts
- lib/core/versions/1.0/TransactionProcessor.ts
- lib/core/versions/latest/TransactionProcessor.ts
- tests/core/MongoDbOperationStore.spec.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/core/Resolver.spec.ts
- tests/core/TransactionProcessor.spec.ts
- tests/mocks/MockOperationStore.ts
> fix(ref-imp): #1019 - Unable to replace a partial operation in DB

- docs/spec/operations.md
> Add concept of anchor origin

- .github/workflows/deploy-spec.yml
See https://github.com/decentralized-identity/sidetree/runs/1921011686
> Fix deployment error due to short commit hash

- docs/spec/title.md
As per #1045 adding myself as a contributor to the spec.
> docs(spec): update contributor list

- docs/spec/title.md
SC approved the status of the work item to reach DIF Ratified Specification title.
> status update

- www/spec/v1.0.0/index.html
Copies the spec status from https://github.com/decentralized-identity/sidetree/pull/1106 into the published version.
> docs(spec): update spec status on v1.0.0 published version

- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/ErrorCode.ts
- lib/core/Core.ts
- lib/core/ErrorCode.ts
- lib/core/MongoDbOperationStore.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/core/Core.spec.ts
feat(ref-imp): only allow DB upgrade on observer node
fix(ref-imp): added index to operation store to support CosmosDB 4.0
> feat(ref-imp): only allow DB upgrade on observer node

- docs/design.md
Experimenting with triggering release action.
> chore(ref-imp): publish release [skip ci]

- lib/bitcoin/BitcoinClient.ts
- tests/bitcoin/BitcoinClient.spec.ts
allow Bitcoin Core to remember list of wallet to load during startup
> fix(ref-imp): allow Bitcoin Core to remember list of wallet to load during startup

- lib/core/Resolver.ts
- lib/core/interfaces/IOperationProcessor.ts
- lib/core/versions/1.0/DocumentComposer.ts
- lib/core/versions/1.0/OperationProcessor.ts
- lib/core/versions/1.0/util/Compressor.ts
- lib/core/versions/latest/OperationProcessor.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/Resolver.spec.ts
- tests/generators/OperationGenerator.ts
Fix to issue raised: https://github.com/decentralized-identity/sidetree/issues/1169
> fix(ref-imp): #1169 - fixed bug on commit-reveal chain leading to infinite loop in resolution

- lib/core/versions/1.0/DocumentComposer.ts
- lib/core/versions/latest/DocumentComposer.ts
- tests/core/DocumentComposer.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/vectors/resolution/afterDeactivate.json
Set `deactivated` DID document metadata property in resolution result of deactivated DID.
Re: #1015, #1052
> fix(ref-imp): set deactivated metadata property

- docs/spec/appendix.md
Encouragement to consider if you should have your own contract numbers represented too. If so, please open issues to track for yourselves, or paste your contract numbers into the suggest changes feature of github.
> Added appendix with DHS references and disclaimers

- lib/core/BlockchainClock.ts
- lib/core/Core.ts
- lib/core/Monitor.ts
- lib/core/interfaces/IBlockchain.ts
- tests/mocks/MockBlockchain.ts
To enable callers provide their own implementation, whilst defaulting to the existing reference implementation
> Enable injection of the blockchain dependency
