- docs/implementation.md
- src/BatchFile.ts
- src/DidCache.ts
- src/Rooter.ts
- tests/DidCache.spec.ts
- tests/RequestHandler.spec.ts
- tests/mocks/MockCas.ts
- tests/mocks/MockDidCache.ts
- tests/mocks/MockDidDocumentGenerator.ts
DID Cache - Fixed a bug in first(...) and improved perf for first(...) and last(...)
DID Cache - Updated the rollback method description to match code.
DID Cache - Fixed all linter errors for tests.
DID Cache - Refactored tests to remove all code duplication.
DID Cache - Fixed obsolete references to lesser().
DID Cache - Updated batch file parsing to adhere to protocol schema + fixed tests.
DID Cache - Renamed method 'prev' to 'previous'.
DID Cache - Removed duplicated test DID Document.
DID Cache - Replaced all incorrect references to 'null' with 'undefined'.
Batch file - Added BatchFile class for parsing and validating batch files.
Rooter - Updated batch file creation to adhere to protocol schema + added test for it.
> Various DID Cache related fixes

- docs/protocol.md
- src/OperationProcessor.ts
- src/RequestHandler.ts
- tests/OperationProcessor.spec.ts
Protocol doc - Fixed typos in Update and Delete REST API examples + other minor fixes.
Operation Processor - Updated resolve() to accept fully qualified DID as input.
With this change Update REST API is officially working.
> Various updates and fixes to enable Update REST API

- package-lock.json
- package.json
- src/Cas.ts
- src/Encoder.ts
- src/OperationProcessor.ts
- src/lib/Cryptography.ts
- src/lib/Did.ts
- src/lib/DidPublicKey.ts
- tests/Operation.spec.ts
- tests/OperationProcessor.spec.ts
- tests/RequestHandler.spec.ts
- tests/generators/OperationGenerator.ts
- tests/generators/VegetaLoadGenerator.ts
- Signature verification - Added support for SECP256K1 key in HEX format. This was mainly added because the implementation of this signature verification library is multiple times faster than `EcKey`. In longer term, JWK support should switch over to the `secp256k1` implementation also if possible.
- Encoder - Fixed a bug where decodeAsBuffer was not decoding correctly.
- CAS client - Fixed a bug where files larger than 64KB gets truncated when fetching.
> Added support for SECP256K1 key in HEX format + a couple of critical bug fixes.

- lib/MongoDbOperationStore.ts
To avoid floating point comparison surprises
> Convert to long before storing numbers in mongodb

- lib/bitcoin/README.md
Removed all references to `bitcore`.
Removed reference to ION.
> Updated Sidetree Bitcoin microservice README

- lib/bitcoin/BitcoinProcessor.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
1. Refactoring of the getUnspentCoins function in BitcoinProcessor.ts:
- Replace deprecated BCoin node API call `/coin/address/$address` by `/tx/address/$address` (refer to [BCoin changelog](https://github.com/bcoin-org/bcoin/blob/master/CHANGELOG.md) Node API changes section.
- Insert additional code to generate unspent transactions from all transaction outputs retrieved with the new API call.
This fix should solve [issue ](https://github.com/decentralized-identity/ion/issues/23).
2. Fixing typo in console.log text in BitcoinProcessor.ts
3. Updating BitcoinProcessor.spec.ts in line with changes in 1.
> Fix BitcoinProcessor.ts getUnspentCoins function

- lib/common/ErrorCode.ts
- lib/core/BatchFile.ts
- lib/core/BatchWriter.ts
- lib/core/Blockchain.ts
- lib/core/Core.ts
- lib/core/MongoDbOperationStore.ts
- lib/core/Observer.ts
- lib/core/Operation.ts
- lib/core/RequestHandler.ts
- src/core.ts
- tests/core/MongoDbOperationStore.spec.ts
- tests/core/Operation.spec.ts
- tests/core/OperationProcessor.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/mocks/MockBlockchain.ts
- tests/mocks/MockOperationStore.ts
1. Made API for fetching blockchain time async (`approximateTime`).
1. Added caching of blockchain time to improve perf.
1. Improved request response to return error codes if any.
1. Added bad request handling to disallow multiple operations for the same DID.
1. Enforced `Operation` instances to always have a DID unique suffix.
> Issue #161 - Added caching of blockchain time + many code improvements.

- docs/protocol.md
- lib/common/ErrorCode.ts
- lib/core/BatchWriter.ts
- lib/core/Core.ts
- lib/core/MongoDbOperationQueue.ts
- lib/core/OperationQueue.ts
- lib/core/RequestHandler.ts
- package.json
- src/core.ts
- tests/core/MongoDbOperationQueue.spec.ts
- tests/core/RequestHandler.spec.ts
- tests/mocks/MockOperationQueue.ts
* Issue #173 - Implemented rule of 1 operation per DID per batch.
* Updated protocol documentation to include 1 operation per DID per batch rule.
* Issue #211 - Persisted operations queued to be anchored in case of a node crash.
* Added tests with 100% code coverage on MongoDB operation queue implementation.
> Issue #173 & #211 - Implemented rule of 1 operation per DID per batch.

- docs/implementation.md
- docs/protocol.md
- lib/bitcoin/BitcoinProcessor.ts
- lib/common/MongoDbTransactionStore.ts
- lib/common/models/TransactionModel.ts
- lib/core/Blockchain.ts
- lib/core/MongoDbUnresolvableTransactionStore.ts
- lib/core/interfaces/IBlockchain.ts
- lib/core/interfaces/IUnresolvableTransactionStore.ts
- lib/core/versions/latest/TransactionProcessor.ts
- lib/core/versions/latest/protocol-parameters.json
- src/bitcoin.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/core/MongoDbTransactionStore.spec.ts
- tests/core/MongoDbUnresolvableTransactionStore.spec.ts
- tests/core/Observer.spec.ts
- tests/mocks/MockBlockchain.ts
- tests/mocks/MockTransactionStore.ts
This is to remove the assumption that the string will always be just an Anchor File hash, which could be untrue as protocol version progresses and evolves.
> Issue #269 - Generalized anchorFileHash as anchorString in transactions.

- docs/implementation.md
- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/fee/SlidingWindowQuantileCalculator.ts
- lib/bitcoin/models/ProtocolParameters.ts
- lib/bitcoin/protocol-parameters.json
- lib/common/SharedErrorCode.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/bitcoin/pof/SlidingWindowQuantileCalculator.spec.ts
Following changes are in this PR:
1. The ```feeApproximation``` protocol parameter has been removed. Instead the code now uses the hardcoded value.
1. Renamed the ```lastSeenBlock``` to ```lastProcessedBlock``` in ```BitcoinProcessor.ts```.
1. The ```lastProcessedBlock``` is now only being updated in the ```processTransactions``` function. This ensures that the status of this variable is up to date even during the revert process.
1. The ```getNormalizedFee``` function now checks against the ```lastProcessedBlock``` to ensure that the correct quantile value can be returned.
> #216 Updating the proof of fee changes to address leftover issues

- lib/bitcoin/BitcoinClient.ts
- lib/bitcoin/models/BitcoinLockTransactionModel.ts
- tests/bitcoin/BitcoinClient.spec.ts
Added following functionality to the BitcoinClient for the lock monitor changes coming next:
1. Functions to create lock, relock, and releaselock transactions.
1. Function to broadcast the lock transactions.
1. Function to return the public key hash of the wallet.
Also, added a couple of fields to the BitcoinLockTransactionModel object.
> #271 Adding functions to the bitcoin client needed for the lockmonitor.

- lib/ipfs/@types/ipfs/index.d.ts
In response to #159 
There were only two such occurrences that I found (referencing the same task). Let me know if you would rather me leave the TODOs, create an issue to track it, and put the link in the comments.
> Remove all TODOs without a github issue reference in code

- docs/spec/markdown/context.md
Generalizes publicKeyJwk to not be specific to secp256k1
> spec: make public key context generic

- lib/core/versions/latest/AnchorFile.ts
- lib/core/versions/latest/MapFile.ts
- lib/core/versions/latest/TransactionProcessor.ts
- lib/core/versions/latest/UpdateOperation.ts
- tests/core/TransactionProcessor.spec.ts
- tests/generators/VegetaLoadGenerator.ts
- tests/generators/vegeta.ts
Fixed the following bugs:
1. We are serializing and storing the complex operation objects as opposed to just the raw operation buffer in MongoDB.
1. The ID for service endpoints in operations generated  by load generator is too long thus get invalidated by resolver.
> Should not store complex operation objects in DB

- lib/core/versions/latest/protocol-parameters.json
The value is based on the bitcoin -> USD converter today.
Using the formula in the linked issue #519 calculated the value for the protocol parameter.
`[Satoshis equivalent to $100K] = 10000 * 25000 * 0.01 * valueTimeLockAmountMultiplier`
`valueTimeLockAmountMultiplier = [Satoshis equivalent to $100K] / 2500000`
Today $100K == 14.42 BTC (approx) == 1447188475 satoshis (approx)
Plugging in the formula above yields the value of `578`. I rounded it to `600` and using that value. This means that for max operations per batch (10K), the required lock amount == 1,500,000,000 satoshis == $103649 (approx) today.
> #519 Updating the valueTimeLockAmountMultiplier

- spec/markdown/rest-api.md
- specs.json
This PR adds the resolution endpoint REST API specification. As compared to the original API:
- Path moves from `[server_url]` `/` to `[server_url]` `/sidetree/` (to align with the swagger).
- JSON object with DID document and metadata is returned, rather than just the DID document.
The companion PR #557 contains the operations endpoint.
> Sidetree resolution REST API spec

- spec/markdown/rest-api.md
This PR adds the operations endpoint REST API specification. As compared to the original API:
- Path moves from `[server_url]` `/` to `[server_url]` `/sidetree/operations` (to align with the swagger).
- Underscore convention is used rather than snake-case.
- s/patchData/operation_data/g
Suggested Followups:
- suffix_data needs more clear definition (https://github.com/decentralized-identity/sidetree/issues/550).
- swagger for operations needs to be updated.
- add DID resolution to spec (not just swagger) including metadata for published flag.
> Sidetree operations REST API spec

- spec/markdown/rest-api.md
Based on https://github.com/decentralized-identity/sidetree/issues/550#issuecomment-613662198, this PR renames `operation_data` => `delta`.
> Use delta in REST API section

- spec/markdown/rest-api.md
- references the [DID Resolution HTTP(S) binding](https://w3c-ccg.github.io/did-resolution/#bindings-https).
- notes that the create operation also returns the DID resolution result.
- notes that method metadata also includes `operationPublicKeys` and `recoveryKey`.
Followups:
- Should we document additional details from DID Resolution binding. Examples:
-  The server MUST include the `Content-Type` header, with the value set to `application/did+ld+json`.
- Questions posed in https://github.com/decentralized-identity/sidetree/issues/571
- Should `published` (eventually) be moved to resolverMetadata?
> Reference DID Resolution spec in REST API

- lib/core/versions/latest/Did.ts
- lib/core/versions/latest/DocumentComposer.ts
- tests/core/Did.spec.ts
- tests/core/DocumentComposer.spec.ts
1. #582 - Removed network ID in -<method>-initial-state.
1. #583 - Used short fragments in `authentication` when referencing keys in `publicKey`.
1. Added/changed unit tests to prevent future regression.
> #582, #583 - Removed network ID in -<method>-initial-state + used short fragments in `authentication`

- README.md
- spec/markdown/file-structures.md
We were referring to the DID Suffix of operations of any type. However,
Create operations do not have a DID Suffix (while Update, Deactivate and
Recover operations do). We defined the DID Suffix of Create operations
as the suffix that their suffix_data field produce
> Clarify reference to DID Suffix of Create operations

- api/markdown/content.md
Recent edits were lost during the content move. This change restores
those edits.
See https://github.com/decentralized-identity/sidetree/commit/abd82b62d756a024569d232309637db47453267d
> Restore latest REST API doc

- api/markdown/content.md
- docs/swagger/api.yml
- resolution endpoint (`<base URL>/sidetree`) is renamed to `<base URL>/identifiers`
- operations endpoint (`<base URL>/sidetree/operations`) is renamed to `<base URL>/operations`
> Remove sidetree path from REST API

- lib/core/versions/latest/DeactivateOperation.ts
- lib/core/versions/latest/DocumentComposer.ts
- lib/core/versions/latest/ErrorCode.ts
- lib/core/versions/latest/MapFile.ts
- lib/core/versions/latest/OperationProcessor.ts
- lib/core/versions/latest/RecoverOperation.ts
- lib/core/versions/latest/UpdateOperation.ts
- tests/core/AnchorFile.spec.ts
- tests/core/DeactivateOperation.spec.ts
- tests/core/Multihash.spec.ts
- tests/core/Operation.spec.ts
- tests/core/RecoverOperation.spec.ts
- tests/core/UpdateOperation.spec.ts
- tests/generators/OperationGenerator.ts
1. Updated property names for update, recover, and deactivate operation requests per spec.
1. Added a few tests to boots code coverage.
> #563 - Updated property names for update, recover, and deactivate operation requests per spec

- docs/protocol.md
The current API spec describes the delta_hash property in terms of the delta property -- but if I understand correctly, it's actually a hash of the decoded (but still JSON stringified / canonicalized) delta property.
> Clarify delta_hash definition in REST API spec

- docs/api/content.md
Removed reveal values from API spec as we are moving towards using public key hash as commitment and public key as reveal.
> #697, #726 - Removed reveal values from API spec

- lib/core/versions/0.9.0/models/PublicKeyModel.ts
- lib/core/versions/latest/Document.ts
- lib/core/versions/latest/DocumentComposer.ts
- lib/core/versions/latest/models/DocumentModel.ts
- lib/core/versions/latest/models/PublicKeyModel.ts
- tests/core/DocumentComposer.spec.ts
I've been running into an error with a `create` operation that invokes `add-public-keys` patches: the DocumentComposer fails because it tries to treat a missing `public_keys` property as an array.
This adds an explicit interface-level indication that `public_keys` may be absent, and adds a test to ensure that `add-public-keys` works against an empty doc.
> Handle the initial case where no keys are present in a Document

- tests/core/DocumentComposer.spec.ts
- tests/generators/OperationGenerator.ts
Fixed the following errors: 
- Error: sidetree/tests/generators/OperationGenerator.ts(70)
Type '{ id: string; type: string; jwk: JwkEs256k; purpose: string[]; }' is not assignable to type 'PublicKeyModel'.
Types of property 'purpose' are incompatible.
Type 'string[]' is not assignable to type 'PublicKeyPurpose[]'.
Type 'string' is not assignable to type 'PublicKeyPurpose'.
- tests/core/DocumentComposer.spec.ts:15:90 - error TS2345: Argument of type '"auth"[]' is not assignable to parameter of type 'PublicKeyPurpose[]'.
Type '"auth"' is not assignable to type 'PublicKeyPurpose'.
15       const [authPublicKey] = await OperationGenerator.generateKeyPair('authePbulicKey', ['auth']);
- tests/core/DocumentComposer.spec.ts:59:90 - error TS2345: Argument of type '"auth"[]' is not assignable to …
> Fixed bugs - type checking

- www/swagger/api.yml
Signed-off-by: Tomislav Markovski <tmarkovski@gmail.com>
Updated swagger to be valid OAS3 spec. Consolidated error response in a single schema. Moved individual error codes to description.
This allows generators to correctly generate code. In addition, strongly typed languages generally prefer defined models in components, instead inline schema.
I tested this with autorest and NSwag, generated C# and typescript code, it looked fine.
> Update swagger spec to valid OAS3 format

- docs/api/content.md
Updates API spec to match swagger - returns 410 for deactivated.
Closes: #780
> Supply response code for deactivated in API spec

- lib/bitcoin/BitcoinClient.ts
- lib/bitcoin/BitcoinWallet.ts
- lib/bitcoin/interfaces/IBitcoinWallet.ts
- tests/bitcoin/BitcoinClient.spec.ts
- tests/bitcoin/BitcoinWallet.spec.ts
See issue #838 for motivations behind this change.
> refactor(ref-imp): Separating the freeze txn signing from the sidetree transaction signing

- lib/bitcoin/BitcoinRawDataParser.ts
- lib/core/versions/0.9.0/RequestHandler.ts
- lib/core/versions/latest/RequestHandler.ts
- tests/bitcoin/BitcoinRawDataParser.spec.ts
- tests/core/TransactionSelector.spec.ts
1. Include the regtest network magic value and validation in parseRawDataFile.
2. Add logic to handle determining blockheight for regtest blocks 1-16
3. Change error message to reflect additional network availability
4. Modify test to accomodate changed error message.
5. Fix unhandled Promise in tests/core/TransactionSelector.spec.ts causing failure of 'npm run lint'.
> feat(ref-imp): add support for bitcoin regtest network

- lib/bitcoin/BitcoinClient.ts
- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/IBitcoinConfig.ts
- lib/core/versions/latest/DocumentComposer.ts
- tests/bitcoin/BitcoinClient.spec.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/core/Did.spec.ts
This PR adds a new config setting `estimatedFeeInBitcoinsPerKB: number | undefined` to be used when the `estimatesmartfee` RPC call fails. There are plenty of occasions when that RPC call fails, most prominently when using bitcoind in `-regtest` or even on testnet where there's less traffic.
Smaller changes in this PR include renames of private APIs (`Kb` to `KB` to signify kilobyte), typos, and existing lint errors.
> Handle estimatesmartfee errors

- lib/core/versions/latest/AnchorFile.ts
- lib/core/versions/latest/BatchWriter.ts
- lib/core/versions/latest/ErrorCode.ts
- lib/core/versions/latest/InputValidator.ts
- lib/core/versions/latest/MapFile.ts
- lib/core/versions/latest/TransactionProcessor.ts
- lib/core/versions/latest/models/AnchorFileModel.ts
- lib/core/versions/latest/models/MapFileModel.ts
- tests/core/AnchorFile.spec.ts
- tests/core/CoreProofFile.spec.ts
- tests/core/MapFile.spec.ts
- tests/core/Observer.spec.ts
- tests/core/TransactionProcessor.spec.ts
- tests/generators/FileGenerator.ts
- tests/generators/OperationGenerator.ts
1. Moved `provisionalProofFileUri` from anchor file into map file.
1. Added more critical checks to ensure integrity between files of a given batch.
1. `composeAnchoredOperationModels` now uses core and provisional proof files for composing signed data.
> feat(ref-imp): #766 - SIP 1 - Moved provisionalProofFileUri into map (provisional index) file

- docs/spec/json-web-signatures.md
Possibly the language regarding how to verify a JWS that contains no key identifier needs to be updated as well.
> Change kid requirements for JWS headers to a MAY

- docs/spec/json-web-signatures.md
This PR introduces the concept of a stale operation.
A Sidetree-based DID Method may reject stale operations. An operation is considered stale relative to the timing information provided by the underlying anchoring system. When an operation is stale according to the DID method’s parameters, the operation is deemed as invalid.
> Add concept of operation anchor timing and validity

- .github/workflows/release.yml
- .github/workflows/unstable-release.yml
- docs/release-process.md
- package.json
Because of https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/, we can no longer use `skip ci` string as the conditional check in our gibhub actions.
> fix(ref-imp): fixed release github actions

- lib/core/versions/latest/DocumentComposer.ts
- tests/core/DocumentComposer.spec.ts
- tests/vectors/resolution/afterCreate.json
- tests/vectors/resolution/afterRecover.json
- tests/vectors/resolution/afterUpdate.json
- tests/vectors/resolution/longFormResponseDidDocument.json
This is a bit of a hack that's potentially going to create issues when resolving
a key that's not controlled by the controller of the did document. At this point
though that's an exceptional case that doesn't need to be handled immediately and
this fix allows DID Documents resolved by the sidetree node to be compliant with
the did-test-suite.
BREAKING CHANGE: The controller is no longer an empty string and instead matches
the document id property (e.g. the did being resolved)
fixes #1152
> fix(ref-imp): fixes controller property to be the short form of the did

- lib/core/Blockchain.ts
- tests/core/Blockchain.spec.ts
- tests/core/MongoDbOperationQueue.spec.ts
Existing code parses too early, preventing other error handling code to take place.
> fix(ref-imp): refactored getWriterValueTimeLock() to handle error better

- lib/bitcoin/BitcoinClient.ts
- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/ErrorCode.ts
- lib/bitcoin/TransactionNumber.ts
- lib/core/Core.ts
- lib/core/interfaces/ITransactionSelector.ts
- tests/bitcoin/BitcoinClient.spec.ts
- tests/bitcoin/BitcoinProcessor.spec.ts
- tests/bitcoin/TransactionNumber.spec.ts
- tests/core/Core.spec.ts
This was discovered in https://github.com/decentralized-identity/ion/issues/240
As a result, rewrote how transaction number is constructed to produce a smaller integer. Also took the opportunity to make the transaction number much more human-friendly also, the current transaction number format had been annoying me for a long time.
Specifically, the current transaction number is simply a large ugly looking number that doesn't make any sense to a human. It would be much easier to make sense of (thus debug), now that a transaction on index position 500 in block 777777 is 777777000500, as opposed to 3340526778581492. Notice the number is smaller AND easier to make sense of.
Also, due to this internal transaction number scheme change, both core and blockchain service will be required to be …
> fix(ref-imp): fixed an integer precision bug in how transaction number is constructed

- www/spec/v1.0.0/index.html
The other protocol parameters have ids, that enable anchor links, e.g.:
https://identity.foundation/sidetree/spec/v1.0.0/#max-operation-hash-length
> Add id for max operation count parameter

- lib/bitcoin/BitcoinClient.ts
- lib/bitcoin/BitcoinProcessor.ts
- lib/bitcoin/models/BitcoinBlockModel.ts
- lib/ipfs/Ipfs.ts
- tests/bitcoin/BitcoinClient.spec.ts
- tests/ipfs/Ipfs.spec.ts
This has been an ask from many people for a while and finally got around to implement it:
- https://github.com/decentralized-identity/sidetree/issues/692
- https://github.com/decentralized-identity/ion/issues/150
In summary, up until now, the Sidetree Bitcoin service expects Bitcoin Core to be in a fully sync-ed and ready state when it starts up, it exits if Bitcoin Core isn't ready to serve requests.
This behavior had been fine for deployment frameworks like kubernetes which restarts the service automatically. But painful for manual setups. This will also help simplify dockerization, because we can now fire-and-forget after starting the container.
Also used this opportunity to add better logging and more documentation on the "fast initialization" code.
> feat(ref-imp): added built-in polling for Bitcoin Core readiness

- lib/bitcoin/BitcoinProcessor.ts
- lib/core/Core.ts
- tests/core/Core.spec.ts
Core service can fail on startup during DB initialization in `docker-compose` when mongoDB is also being spun up and not ready to serve requests. This PR fixes that.
> Added DB initialization retry on startup for better docker support

- lib/common/MongoDbStore.ts
- package-lock.json
- package.json
Update to mongo db version to prevent error as noted here: https://jira.mongodb.org/browse/NODE-3252.
Previously if Mongo lost connection it would not recover without restarting the sidetree consuming app. This change makes the connection recover and sidetree processing to resume without restarting.
> fix(ref-imp): update mongo db version

- lib/index.ts
Follow-up to https://github.com/decentralized-identity/sidetree/pull/1203
This PR further facilitates the injection of the blockchain dependency by _exporting_ the interfaces from which it is composed
> Add exports for blockchain service class and interfaces
